import type { DisplayLocale, HomeCopy, LocaleOption, ProjectMockVariant } from "./types";

export const DEFAULT_LOCALE: DisplayLocale = "zhHant";
export const LOCALE_STORAGE_KEY = "interactive_presentation_language";

export const localeOptions: LocaleOption[] = [
  { id: "zh", label: "简" },
  { id: "zhHant", label: "繁" },
  { id: "en", label: "EN" },
  { id: "ja", label: "日" },
  { id: "ko", label: "한" },
];

export const homeCopy: Record<DisplayLocale, HomeCopy> = {
  zh: {
    title: "Omnistack 让创意直达产品",
    description: "从需求到量产，以自然语言驱动人机交互产品的全链路创新",
    placeholder: "输入你的界面需求、风格方向或控件调整指令",
    upload: "上传文件 / 图片",
    generate: "->",
    fileHint: "支持 .ai、.psd、.html、.figma、.zip、.md、.png、.jpg、.jpeg",
    selectedFiles: (count) => "已选择 " + count + " 个文件",
    projects: "项目列表",
    projectTitle: "个人项目",
    projectDesc: "选择一个已有项目，继续编辑节点关系与 UI 页面。",
    settings: "设置",
    language: "语言设置",
    guide: "工具说明",
    guideTitle: "工具说明",
    guideSubtitle: "按 ESC 可退出说明窗口",
    loading: "项目加载中...",
    recent: "最近打开",
    unopened: "未打开",
    projectNamePrefix: "项目",
    sections: [
      { title: "一、工具定位", body: "这个原型用于演示通过自然语言、图像或结构指令生成界面，并继续沉淀需求文档、界面方案和预览结果。" },
      { title: "二、支持内容", body: "当前支持上传设计稿、图片、网页文件与文档内容，系统会模拟识别结构层级、视觉语气、组件关系与页面流转。", showDemo: true },
      { title: "三、交互方式", body: "首页用于描述需求，项目弹层用于选择已有项目，设置弹层用于切换语言和查看工具说明。" },
      { title: "四、推荐描述", body: "示例：我要一个冷灰底、纯白卡片、黑色文字、工业橙强调的设备控制界面，按钮偏圆角，布局保持克制。", links: ["查看 UI 生成规范", "查看组件调整说明", "查看交互原型示例"] },
      { title: "五、当前范围", body: "本阶段先还原原型首页，不展示线程、PRD、硬件运行等原型首页没有的功能。" },
    ],
  },
  zhHant: {
    title: "Omnistack 讓創意直達產品",
    description: "從需求到量產，以自然語言驅動人機互動產品的全鏈路創新",
    placeholder: "輸入你的介面需求、風格方向或控制項調整指令",
    upload: "上傳檔案 / 圖片",
    generate: "->",
    fileHint: "支援 .ai、.psd、.html、.figma、.zip、.md、.png、.jpg、.jpeg",
    selectedFiles: (count) => "已選擇 " + count + " 個檔案",
    projects: "專案列表",
    projectTitle: "個人專案",
    projectDesc: "選擇一個已有專案，繼續編輯節點關係與 UI 頁面。",
    settings: "設定",
    language: "語言設定",
    guide: "工具說明",
    guideTitle: "工具說明",
    guideSubtitle: "按 ESC 可退出說明視窗",
    loading: "專案載入中...",
    recent: "最近開啟",
    unopened: "未開啟",
    projectNamePrefix: "專案",
    sections: [
      { title: "一、工具定位", body: "這個原型用於演示透過自然語言、圖像或結構指令生成介面，並繼續沉澱需求文件、介面方案和預覽結果。" },
      { title: "二、支援內容", body: "目前支援上傳設計稿、圖片、網頁檔案與文件內容，系統會模擬識別結構層級、視覺語氣、元件關係與頁面流轉。", showDemo: true },
      { title: "三、互動方式", body: "首頁用於描述需求，專案彈層用於選擇已有專案，設定彈層用於切換語言和查看工具說明。" },
      { title: "四、推薦描述", body: "示例：我要一個冷灰底、純白卡片、黑色文字、工業橙強調的設備控制介面，按鈕偏圓角，佈局保持克制。", links: ["查看 UI 生成規範", "查看元件調整說明", "查看互動原型示例"] },
      { title: "五、目前範圍", body: "本階段先還原原型首頁，不展示執行緒、PRD、硬體執行等原型首頁沒有的功能。" },
    ],
  },
  en: {
    title: "let ai draft your interface system",
    description: "Start from a single prompt and shape a colder, sharper interface language with pale gray surfaces, clean white panels, and industrial orange accents.",
    placeholder: "Describe your UI request, visual tone, or control adjustments",
    upload: "Upload Files / Images",
    generate: "->",
    fileHint: "Supports .ai, .psd, .html, .figma, .zip, .md, .png, .jpg, .jpeg",
    selectedFiles: (count) => count + " files selected",
    projects: "Project List",
    projectTitle: "Personal Projects",
    projectDesc: "Choose an existing project and continue editing node relationships and UI screens.",
    settings: "Settings",
    language: "Language",
    guide: "Guide",
    guideTitle: "Guide",
    guideSubtitle: "Press ESC to close the guide window",
    loading: "Loading projects...",
    recent: "Recently opened",
    unopened: "Not opened",
    projectNamePrefix: "Project",
    sections: [
      { title: "1. Positioning", body: "This prototype demonstrates how natural language, imagery, and structured prompts generate interface directions and reviewable UI artifacts." },
      { title: "2. Supported Inputs", body: "You can upload design files, images, web files, and documents. The system simulates parsing hierarchy, visual tone, component relationships, and navigation flow.", showDemo: true },
      { title: "3. Workflow", body: "The home page captures intent, the project layer selects existing projects, and the settings layer controls language and guide content." },
      { title: "4. Prompt Direction", body: "Example: build a hardware control interface with a pale gray background, white cards, black type, and high-saturation industrial orange accents.", links: ["View UI generation notes", "View component editing notes", "View interaction examples"] },
      { title: "5. Current Scope", body: "This stage restores the prototype home first, without thread lists, PRD panels, or hardware runtime areas." },
    ],
  },
  ja: {
    title: "AI で UI を組み立てる",
    description: "淡いグレーの背景、白いパネル、強い工業オレンジを基調にした UI を、ひとつの指示文から組み立てます。",
    placeholder: "UI 要件、雰囲気、または調整したい内容を入力してください",
    upload: "ファイル / 画像をアップロード",
    generate: "->",
    fileHint: ".ai, .psd, .html, .figma, .zip, .md, .png, .jpg, .jpeg に対応",
    selectedFiles: (count) => count + " 個のファイルを選択済み",
    projects: "プロジェクト一覧",
    projectTitle: "個人プロジェクト",
    projectDesc: "既存のプロジェクトを選び、ノード関係と UI 画面の編集を続けます。",
    settings: "設定",
    language: "言語",
    guide: "ガイド",
    guideTitle: "ガイド",
    guideSubtitle: "ESC キーでガイドを閉じます",
    loading: "読み込み中...",
    recent: "最近開いた",
    unopened: "未オープン",
    projectNamePrefix: "プロジェクト",
    sections: [
      { title: "1. 位置づけ", body: "この試作は、自然言語や画像から UI の方向性を生成し、その後ドキュメントとプレビューを確認する流れを示します。" },
      { title: "2. 対応入力", body: "デザインファイル、画像、Web ファイル、文書をアップロードできます。構造、雰囲気、コンポーネント関係、画面遷移を模擬解析します。", showDemo: true },
      { title: "3. 操作の流れ", body: "ホームで要件を入力し、プロジェクトレイヤーで既存プロジェクトを選び、設定で言語とガイドを確認します。" },
      { title: "4. 推奨プロンプト", body: "例: 薄いグレー背景、白いカード、黒い文字、工業オレンジ強調の設備 UI を作りたい。", links: ["UI 生成メモを見る", "コンポーネント調整メモを見る", "操作例を見る"] },
      { title: "5. 現在の範囲", body: "この段階ではホームを優先し、スレッド、PRD、ハードウェア実行領域は表示しません。" },
    ],
  },
  ko: {
    title: "AI가 인터페이스를 설계하도록",
    description: "연한 회색 배경, 순백 패널, 강한 산업용 오렌지 포인트를 가진 UI를 한 줄의 프롬프트에서 시작합니다.",
    placeholder: "UI 요구사항, 스타일 방향, 조정할 내용을 입력하세요",
    upload: "파일 / 이미지 업로드",
    generate: "->",
    fileHint: ".ai, .psd, .html, .figma, .zip, .md, .png, .jpg, .jpeg 지원",
    selectedFiles: (count) => count + "개 파일 선택됨",
    projects: "프로젝트 목록",
    projectTitle: "개인 프로젝트",
    projectDesc: "기존 프로젝트를 선택해 노드 관계와 UI 화면 편집을 이어갑니다.",
    settings: "설정",
    language: "언어",
    guide: "가이드",
    guideTitle: "가이드",
    guideSubtitle: "ESC 키로 가이드 창을 닫을 수 있습니다",
    loading: "프로젝트 불러오는 중...",
    recent: "최근 열림",
    unopened: "열지 않음",
    projectNamePrefix: "프로젝트",
    sections: [
      { title: "1. 도구 성격", body: "이 프로토타입은 자연어와 이미지를 통해 UI 방향을 만들고, 이후 문서와 미리보기를 확인하는 흐름을 보여줍니다." },
      { title: "2. 지원 입력", body: "디자인 파일, 이미지, 웹 파일, 문서를 업로드할 수 있습니다. 구조, 분위기, 컴포넌트 관계, 페이지 흐름을 모의 분석합니다.", showDemo: true },
      { title: "3. 사용 흐름", body: "홈에서 요구사항을 입력하고, 프로젝트 레이어에서 기존 프로젝트를 선택하며, 설정에서 언어와 가이드를 확인합니다." },
      { title: "4. 추천 프롬프트", body: "예시: 연한 회색 배경, 흰 카드, 검은 텍스트, 산업용 오렌지 포인트를 가진 장비 제어 UI를 만들고 싶다.", links: ["UI 생성 메모 보기", "컴포넌트 조정 메모 보기", "인터랙션 예시 보기"] },
      { title: "5. 현재 범위", body: "이 단계에서는 홈 화면을 먼저 복원하고, 스레드, PRD, 하드웨어 실행 영역은 표시하지 않습니다." },
    ],
  },
};

export const projectMockVariants: ProjectMockVariant[] = [
  { screen: "linear-gradient(135deg, #f7f7f8, #e9ecef)", blocks: ["mock-nav", "mock-title", "mock-row"] },
  { screen: "linear-gradient(135deg, #f8f8f8, #eceff1)", blocks: ["mock-side", "mock-content"] },
  { screen: "linear-gradient(135deg, #ffffff, #ececec)", blocks: ["mock-phone", "mock-lines"] },
  { screen: "linear-gradient(135deg, #fff6f1, #ffe0d0)", blocks: ["mock-card-a", "mock-card-b"] },
  { screen: "linear-gradient(135deg, #f5f6f7, #e6eaee)", blocks: ["mock-dashboard"] },
];
