export type Locale = "en" | "zh";

export interface UIStrings {
  // Welcome
  welcomeTitle: string;
  welcomeSubtitle: string;

  // Composer
  composerPlaceholder: string;
  composerAriaLabel: string;
  sendMessageAriaLabel: string;
  stopGeneratingAriaLabel: string;

  // Tooltips / action bar
  scrollToBottom: string;
  sendMessage: string;
  stopGenerating: string;
  copy: string;
  refresh: string;
  more: string;
  edit: string;
  previous: string;
  next: string;

  // Edit composer
  cancel: string;
  update: string;

  // More menu
  exportMarkdown: string;

  // Thinking phrases (cycling)
  thinkingPhrases: string[];

  // Tool group / tool fallback
  toolCalls: (count: number) => string;
  usedTool: string;
  cancelledTool: string;

  // Reasoning
  reasoning: string;

  // Thread list / sidebar
  newThread: string;
  loadMore: string;
  appName: string;

  // Canvas
  previewCanvas: string;
  live: string;
  welcomeTab: string;
  prdTab: string;
  uiTab: string;
  canvasEmpty: string;
  canvasEmptyDesc: string;
  prdNotGenerated: string;
  slintNotGenerated: string;
  btnPreview: string;
  btnBuild: string;
  btnRunOnHardware: string;
  btnDeploying: string;
  btnRunOnHardwareNoDevice: string;

  // Welcome tab
  welcomeGreeting: string;
  supportedHardwareTitle: string;
  connectedHardwareTitle: string;
  noConnectedHardware: string;
  usageTitle: string;
  usageSteps: string[];

  // Project gate
  loading: string;

  // Project switcher
  projectsLabel: string;
  newProjectMenuItem: string;

  // Create project dialog
  newProject: string;
  createFirstProject: string;
  projectDescription: string;
  projectNamePlaceholder: string;
  createButton: string;
  creatingButton: string;

  // Delete project dialog
  deleteButton: string;
  deletingButton: string;
  deleteProjectTitle: (name: string) => string;
  deleteProjectDesc: string;

  // Validation errors
  validationEmpty: string;
  validationReserved: string;
  validationInvalidChars: string;
  validationTooLong: string;
  createFailed: string;
  deleteFailed: string;

  // Suggestions
  suggestions: Array<{
    title: string;
    label: string;
    prompt: string;
  }>;
}

export const en: UIStrings = {
  welcomeTitle: "Hello there!",
  welcomeSubtitle: "What can I build for you today?",

  composerPlaceholder: "Send a message...",
  composerAriaLabel: "Message input",
  sendMessageAriaLabel: "Send message",
  stopGeneratingAriaLabel: "Stop generating",

  scrollToBottom: "Scroll to bottom",
  sendMessage: "Send message",
  stopGenerating: "Stop generating",
  copy: "Copy",
  refresh: "Refresh",
  more: "More",
  edit: "Edit",
  previous: "Previous",
  next: "Next",

  cancel: "Cancel",
  update: "Update",

  exportMarkdown: "Export as Markdown",

  thinkingPhrases: [
    "Thinking",
    "Analyzing",
    "Planning",
    "Reasoning",
    "Generating",
    "Processing",
  ],

  toolCalls: (count) => `${count} tool ${count === 1 ? "call" : "calls"}`,
  usedTool: "Used tool",
  cancelledTool: "Cancelled tool",

  reasoning: "Reasoning",

  newThread: "New Thread",
  loadMore: "Load more",
  appName: "OmniStack UI",

  previewCanvas: "Preview Canvas",
  live: "Live",
  welcomeTab: "Welcome",
  prdTab: "PRD",
  uiTab: "UI",
  canvasEmpty: "Canvas is empty",
  canvasEmptyDesc: "Artifacts generated by the agents will appear here.",
  prdNotGenerated: "PRD not yet generated.",
  slintNotGenerated: "Slint UI not yet generated.",
  btnPreview: "Preview",
  btnBuild: "Build",
  btnRunOnHardware: "Run on Hardware",
  btnDeploying: "Deploying…",
  btnRunOnHardwareNoDevice: "No device connected",

  welcomeGreeting: "Welcome to OmniStack UI — an AI-powered platform for generating embedded Slint UI applications.",
  supportedHardwareTitle: "Supported Hardware",
  connectedHardwareTitle: "Connected Hardware",
  noConnectedHardware: "No hardware connected",
  usageTitle: "Getting Started",
  usageSteps: [
    "Select a project from the sidebar, or create a new one.",
    "Connect your hardware device if you have any.",
    "Describe your UI in the chat — attach screenshots for vision-based generation, better with text description for each screenshot.",
    "Review the PRD and UI previews in the tabs above.",
  ],

  loading: "Loading…",

  projectsLabel: "Projects",
  newProjectMenuItem: "+ New project…",

  newProject: "New Project",
  createFirstProject: "Create your first project",
  projectDescription:
    "A project holds all your threads and generated files in one place.",
  projectNamePlaceholder: "e.g. Smart Thermostat UI",
  createButton: "Create",
  creatingButton: "Creating…",

  deleteButton: "Delete",
  deletingButton: "Deleting…",
  deleteProjectTitle: (name) => `Delete "${name}"?`,
  deleteProjectDesc:
    "All threads and generated files will be permanently deleted. This cannot be undone.",

  validationEmpty: "Project name cannot be empty.",
  validationReserved: "'.' and '..' are reserved names.",
  validationInvalidChars:
    "Project name contains characters not allowed in folder names (e.g. '/' or control characters).",
  validationTooLong: "Project name is too long (max 255 bytes).",
  createFailed: "Failed to create project.",
  deleteFailed: "Failed to delete project.",

  suggestions: [
    {
      title: "Analyze screenshots",
      label: "PRD report",
      prompt: "Attach one or more UI screenshots using the + button, then send to generate a PRD report describing the screens and their relationships.",
    },
    {
      title: "Hello world UI",
      label: "quick start",
      prompt: "Generate a hello world Slint UI with a button.",
    },
    {
      title: "Sensor dashboard",
      label: "full run",
      prompt: "Build a dashboard with status cards and a chart for sensor data.",
    },
    {
      title: "Settings screen",
      label: "ui only",
      prompt: "Create a settings screen with toggles, sliders, and a save button.",
    },
    {
      title: "Login form",
      label: "ui only",
      prompt:
        "Design a login form with username, password, and a submit button.",
    },
  ],
};

export const zh: UIStrings = {
  welcomeTitle: "你好！",
  welcomeSubtitle: "今天想让我帮您构建什么？",

  composerPlaceholder: "发送消息...",
  composerAriaLabel: "消息输入",
  sendMessageAriaLabel: "发送消息",
  stopGeneratingAriaLabel: "停止生成",

  scrollToBottom: "滚动到底部",
  sendMessage: "发送消息",
  stopGenerating: "停止生成",
  copy: "复制",
  refresh: "刷新",
  more: "更多",
  edit: "编辑",
  previous: "上一条",
  next: "下一条",

  cancel: "取消",
  update: "更新",

  exportMarkdown: "导出为 Markdown",

  thinkingPhrases: ["思考中", "分析中", "规划中", "推理中", "生成中", "处理中"],

  toolCalls: (count) => `调用了 ${count} 个工具`,
  usedTool: "调用工具",
  cancelledTool: "已取消工具",

  reasoning: "推理",

  newThread: "新对话",
  loadMore: "加载更多",
  appName: "OmniStack UI",

  previewCanvas: "预览画布",
  live: "实时",
  welcomeTab: "欢迎",
  prdTab: "需求文档",
  uiTab: "界面",
  canvasEmpty: "画布为空",
  canvasEmptyDesc: "智能体生成的内容将在此处显示。",
  prdNotGenerated: "需求文档尚未生成。",
  slintNotGenerated: "Slint UI 尚未生成。",
  btnPreview: "预览",
  btnBuild: "构建",
  btnRunOnHardware: "在硬件上运行",
  btnDeploying: "部署中…",
  btnRunOnHardwareNoDevice: "无已连接设备",

  welcomeGreeting: "欢迎使用 OmniStack UI —— 面向嵌入式 Slint UI 应用的 AI 生成平台。",
  supportedHardwareTitle: "支持的硬件",
  connectedHardwareTitle: "已连接硬件",
  noConnectedHardware: "暂无已连接硬件",
  usageTitle: "快速上手",
  usageSteps: [
    "从侧边栏选择项目，或新建一个项目。",
    "如有硬件设备，请连接您的硬件。",
    "在对话框中描述您的 UI，也可上传截图进行视觉生成，建议为每张截图附上文字说明。",
    "在上方标签页查看生成的需求文档和界面预览。",
  ],

  loading: "加载中…",

  projectsLabel: "项目",
  newProjectMenuItem: "+ 新建项目…",

  newProject: "新建项目",
  createFirstProject: "创建第一个项目",
  projectDescription: "项目包含您的所有对话和生成的文件。",
  projectNamePlaceholder: "例如：智能恒温器界面",
  createButton: "创建",
  creatingButton: "创建中…",

  deleteButton: "删除",
  deletingButton: "删除中…",
  deleteProjectTitle: (name) => `删除"${name}"？`,
  deleteProjectDesc: "所有对话和生成的文件将被永久删除，此操作无法撤销。",

  validationEmpty: "项目名称不能为空。",
  validationReserved: "'.' 和 '..' 是保留名称。",
  validationInvalidChars:
    "项目名称包含文件夹名称中不允许的字符（例如 '/' 或控制字符）。",
  validationTooLong: "项目名称过长（最多 255 字节）。",
  createFailed: "创建项目失败。",
  deleteFailed: "删除项目失败。",

  suggestions: [
    {
      title: "分析截图",
      label: "需求报告",
      prompt: "点击 + 按钮上传一张或多张 UI 截图，然后发送以生成描述各页面及其关系的需求文档报告。",
    },
    {
      title: "Hello World UI",
      label: "快速开始",
      prompt: "生成一个带按钮的 Hello World Slint UI。",
    },
    {
      title: "传感器仪表盘",
      label: "完整运行",
      prompt: "构建一个包含状态卡片和传感器数据图表的仪表盘。",
    },
    {
      title: "设置界面",
      label: "仅 UI",
      prompt: "创建一个带有开关、滑块和保存按钮的设置界面。",
    },
    {
      title: "登录表单",
      label: "仅 UI",
      prompt: "设计一个包含用户名、密码和提交按钮的登录表单。",
    },
  ],
};

export const localeStrings: Record<Locale, UIStrings> = { en, zh };
